"""empty message

Revision ID: 1efd5a33e903
Revises: 62a50969aeef
Create Date: 2017-03-29 22:33:49.369343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1efd5a33e903'
down_revision = '62a50969aeef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songRequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('artist', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songRequest')
    # ### end Alembic commands ###
